### ISSUE TITLE
Publishing package on PyPI

### ISSUE THREAD

**Issue by klb2** [pierre-24/pyiso4#2]
I really like the package and I would like to use it as a dependency for one of my projects. In order for me to update my package on [PyPI](https://pypi.org/), this package also needs to be available there.  
This would have the additional benefit that other users could also install `pyiso4` directly via pip by running `pip install pyiso4`.

Is there a plan to publish this package on PyPI?

**Comment by pierre-24** [comment]
Hello, and thanks! I will try to do that (I have to say that I never uploaded anything on pypi before).

**Comment by klb2** [comment]
Thank you. It is actually very simple. You need to create an account on PyPI and then build and upload the package according to the steps which are described [here](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives). It is a very simple two step process.
Basically, you only need to run the following two commands:

```bash
python3 -m build
python3 -m twine upload dist/*
```

**Comment by pierre-24** [comment]
Actually, you have to use Github actions to do so. So I prep'd everything and now I'm waiting for the go :)

![image](https://github.com/pierre-24/pyiso4/assets/7889675/ec17d274-2b6f-45c7-938e-cf34c98243e3)

**Comment by pierre-24** [comment]
... And it is done, package is live: https://pypi.org/project/pyiso4/ !

**Comment by klb2** [comment]
Great. Thank you!
