### ISSUE TITLE
Wrong behavior with years/numbers in titles

### ISSUE THREAD

**Issue by klb2** [pierre-24/pyiso4#3]
The abbreviation is handling titles with numbers, e.g., years, incorrectly.

**Examples:**

| | Value/String |
|------|-----|
| Input | `Proceedings of the 2024 Conference on Science` |
| Output | `Proc. the4202 Conf. Sci.` |
| Expected Output | `Proc. 2024 Conf. Sci.` or `Proc. Conf. Sci.` |

It seems to work fine when the number is not standalone, e.g., `Proceedings of the 25th Conference on Science` gets abbreviated as `Proc. 25th Conf. Sci.`.

**Comment by pierre-24** [comment]
Ok, that's fixed. You pulled a good one, since there was in fact an issue with how symbols are handled.
